#!/usr/bin/env python3
"""mini_lesson — a CLI tool that generates a mini-lesson from a topic.

Pipeline: identify 3 key concepts → explain each → synthesize takeaway.
Generated by agentic create-app, then cleaned up.
"""

import argparse

from agentic import agentic_function, create_runtime
from agentic.runtime import Runtime


@agentic_function(input={
    "topic": {"description": "Lesson topic", "placeholder": "e.g. quantum computing basics"},
    "runtime": {"hidden": True},
})
def identify_key_concepts(topic: str, runtime: Runtime = None) -> str:
    """Identify 3 key concepts related to the topic.

    Return a numbered list of 3 concepts, each with a one-sentence description.
    """
    return runtime.exec(content=[
        {"type": "text", "text": f"Identify 3 key concepts about: {topic}\n\nReturn a numbered list with one-sentence descriptions."},
    ])


@agentic_function(input={
    "concepts": {"description": "Concepts to explain", "placeholder": "e.g. 1. Superposition ..."},
    "runtime": {"hidden": True},
})
def explain_concepts(concepts: str, runtime: Runtime = None) -> str:
    """Explain each of the identified key concepts in clear, accessible language.

    For each concept, provide a 2-3 sentence explanation with an example.
    """
    return runtime.exec(content=[
        {"type": "text", "text": f"Explain these concepts clearly with examples:\n\n{concepts}"},
    ])


@agentic_function(input={
    "explanation": {"description": "Explanations to synthesize", "placeholder": "The concept explanations..."},
    "runtime": {"hidden": True},
})
def synthesize_takeaway(explanation: str, runtime: Runtime = None) -> str:
    """Synthesize a concise takeaway from the explanations.

    Produce a 2-3 sentence summary that connects the concepts and
    highlights the most important insight.
    """
    return runtime.exec(content=[
        {"type": "text", "text": f"Synthesize a concise takeaway from these explanations:\n\n{explanation}"},
    ])


def main():
    parser = argparse.ArgumentParser(description="Generate a mini-lesson from a given topic.")
    parser.add_argument("topic", help="The topic for the mini-lesson")
    parser.add_argument("--provider", default=None, help="LLM provider override")
    parser.add_argument("--model", default=None, help="Model override")
    args = parser.parse_args()

    runtime = create_runtime(provider=args.provider, model=args.model)

    try:
        concepts = identify_key_concepts(topic=args.topic, runtime=runtime)
        explanation = explain_concepts(concepts=concepts, runtime=runtime)
        takeaway = synthesize_takeaway(explanation=explanation, runtime=runtime)
        print(takeaway)
    finally:
        runtime.close()


if __name__ == "__main__":
    main()
