"""
create_app() — Generate a complete runnable agentic app (runtime + functions + main).

Unlike create() which generates a single function, create_app() generates
a self-contained Python script with:
  - create_runtime() call to set up the LLM provider
  - One or more @agentic_function definitions
  - A main() entry point that orchestrates them
"""

from __future__ import annotations

import os

from agentic.function import agentic_function
from agentic.runtime import Runtime
from agentic.meta_functions._helpers import extract_code


@agentic_function(input={
    "description": {
        "description": "What the app should do",
        "placeholder": "e.g. a CLI tool that summarizes PDF files",
        "multiline": True,
    },
    "runtime": {"hidden": True},
    "name": {
        "description": "App name (used as filename)",
        "placeholder": "app",
        "multiline": False,
    },
})
def create_app(description: str, runtime: Runtime, name: str = "app") -> str:
    """Generate a complete, runnable agentic app script.

    The generated app must be a self-contained Python script that:

    1. Imports from the agentic package:
       ```python
       from agentic import agentic_function, create_runtime
       ```

    2. Creates a runtime with auto-detection (user can override with --provider):
       ```python
       runtime = create_runtime()
       ```

    3. Defines one or more @agentic_function(s) that call runtime.exec().
       Remember: the docstring IS the LLM prompt. Content only passes data.

    4. Has a main() function that orchestrates the agentic functions.
       Python controls the flow (loops, conditionals, error handling).
       The LLM only does reasoning inside @agentic_function calls.

    5. Has an `if __name__ == "__main__":` block with argparse for CLI usage.
       The script should accept relevant arguments (e.g., --input, --topic).

    IMPORTANT — Template structure:

    ```python
    #!/usr/bin/env python3
    \"\"\"<App description>. Generated by agentic create-app.\"\"\"

    import argparse
    from agentic import agentic_function, create_runtime

    runtime = create_runtime()

    @agentic_function
    def step_one(input_data: str) -> str:
        \"\"\"<What this step does — this IS the prompt>.\"\"\"
        return runtime.exec(content=[
            {"type": "text", "text": input_data},
        ])

    @agentic_function
    def step_two(prev_result: str) -> str:
        \"\"\"<What this step does — this IS the prompt>.\"\"\"
        return runtime.exec(content=[
            {"type": "text", "text": prev_result},
        ])

    def main():
        parser = argparse.ArgumentParser(description="<app description>")
        parser.add_argument("input", help="<what the input is>")
        parser.add_argument("--provider", default=None, help="LLM provider override")
        parser.add_argument("--model", default=None, help="Model override")
        args = parser.parse_args()

        global runtime
        runtime = create_runtime(provider=args.provider, model=args.model)

        # Python controls the flow
        result_1 = step_one(input_data=args.input)
        result_2 = step_two(prev_result=result_1)
        print(result_2)

    if __name__ == "__main__":
        main()
    ```

    Rules:
    - The app must be runnable: `python <name>.py <args>`
    - Use create_runtime() — NOT a hardcoded provider class
    - Accept --provider and --model args so users can choose their LLM
    - Python controls ALL flow: loops, conditionals, sequencing
    - LLM ONLY reasons inside @agentic_function via runtime.exec()
    - Standard library imports only (os, json, re, pathlib, etc.)
    - No async/await
    - Write ONLY the Python code. No explanation.

    Args:
        description:  What the app should do.
        runtime:      Runtime instance for the LLM call that generates the app.
        name:         App name (used as filename, default: "app").

    Returns:
        Path to the generated script.
    """
    response = runtime.exec(content=[
        {"type": "text", "text": (
            f"Write a complete, runnable agentic app that does the following:\n\n"
            f"{description}\n\n"
            f"The app name is '{name}'.\n\n"
            f"Respond with ONLY the Python code inside a ```python code fence. "
            f"No explanation, no commentary, no markdown outside the fence."
        )},
    ])
    code = extract_code(response)

    # Validate it's a complete app (has imports and main)
    try:
        compile(code, "<generated_app>", "exec")
    except SyntaxError as e:
        raise SyntaxError(
            f"Generated app has syntax errors:\n{code}\n\nError: {e}"
        ) from e

    # Save to agentic/apps/ directory
    if not os.environ.get("PYTEST_CURRENT_TEST"):
        apps_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "apps")
        os.makedirs(apps_dir, exist_ok=True)
        filepath = os.path.join(apps_dir, f"{name}.py")
        with open(filepath, "w") as f:
            f.write(code + "\n")
        return filepath

    return code
