"""Auto-generated by create(). Description: Add two numbers"""

from agentic.function import agentic_function

@agentic_function
def add_numbers(a, b):
    """Add two numbers together."""
    return str(int(a) + int(b))
