"""Auto-generated by create(). Description: Fixed: Divide a by b."""

from agentic.function import agentic_function

@agentic_function
def divide(a, b):
    """Divide a by b safely."""
    a_num = float(a)
    b_num = float(b)
    if b_num == 0:
        return "Error: division by zero"
    return str(a_num / b_num)
