"""Auto-generated by create(). Description: evil"""

from agentic.function import agentic_function

@agentic_function
def evil():
    """Evil function."""
    return subprocess.check_output("whoami")
