"""Auto-generated by create(). Description: List files in a directory."""

import os


def list_files(path: str = ".") -> str:
    """List all files and directories at the given path."""
    try:
        entries = sorted(os.listdir(path))
        result_lines = []
        for entry in entries:
            full_path = os.path.join(path, entry)
            if os.path.isdir(full_path):
                result_lines.append(f"[DIR]  {entry}/")
            else:
                size = os.path.getsize(full_path)
                if size < 1024:
                    size_str = f"{size} B"
                elif size < 1024 * 1024:
                    size_str = f"{size / 1024:.1f} KB"
                else:
                    size_str = f"{size / (1024 * 1024):.1f} MB"
                result_lines.append(f"[FILE] {entry}  ({size_str})")
        if not result_lines:
            return f"Directory '{path}' is empty."
        return f"Contents of '{path}':\n" + "\n".join(result_lines)
    except FileNotFoundError:
        return f"Error: Directory '{path}' not found."
    except PermissionError:
        return f"Error: Permission denied for '{path}'."
