"""Auto-generated by create(). Description: Fixed: Do something."""

from agentic.function import agentic_function

@agentic_function
def func():
    """Fixed without question."""
    return "no_question"
