"""Auto-generated by create(). Description: Analyze text sentiment."""

from agentic.function import agentic_function


@agentic_function
def sentiment(text: str) -> str:
    """Analyze the sentiment of a given text. Return one word: positive, negative, or neutral."""
    result = runtime.exec(content=[
        {"type": "text", "text": f"Analyze the sentiment of the following text. Respond with exactly one word: positive, negative, or neutral.\n\nText: {text}"},
    ])
    return result.strip().lower()
