"""Auto-generated by create(). Description: Analyze text sentiment."""

from agentic.function import agentic_function


@agentic_function
def sentiment(text: str) -> str:
    """Analyze the sentiment of the given text.
    Return exactly one word: positive, negative, or neutral.

    Args:
        text: The text to analyze.

    Returns:
        One of 'positive', 'negative', or 'neutral'.
    """
    return runtime.exec(content=[{"type": "text", "text": text}])
