"""Auto-generated by create(). Description: Analyze text sentiment."""

from agentic.function import agentic_function
from agentic.runtime import Runtime


@agentic_function(input={
    "text": {
        "description": "Text to analyze",
        "placeholder": "e.g. I love this product! It works perfectly.",
    },
    "runtime": {"hidden": True},
})
def sentiment(text: str, runtime: Runtime = None) -> str:
    """Analyze the sentiment of the given text.
    Return exactly one word: positive, negative, or neutral.

    Args:
        text: The text to analyze.

    Returns:
        One of 'positive', 'negative', or 'neutral'.
    """
    return runtime.exec(content=[{"type": "text", "text": text}])
