"""Auto-generated by create(). Description: Summarize text"""

from agentic.function import agentic_function

@agentic_function
def summarize(text):
    """Summarize the given text into a short sentence."""
    return runtime.exec(content=[
        {"type": "text", "text": "Summarize in one sentence: " + text},
    ])
